# <font color = 'green'><b><center>Pandas</center>

In [3]:
import pandas as pd
import numpy as np

## Table of Contents

1. **Working with Pandas Series**
   * **a) Creating Series**
     * Series through list
     * Series through Numpy Array
     * Setting up our own index
     * Series through dictionary
     * Using repeat function along with creating a Series
     * Accessing data from Series
   * **b) Aggregate function on Pandas Series**
   * **c) Series Absolute Function**
   * **d) Appending Series**
   * **e) Astype Function**
   * **f) Between Functions**
   * **g) All strings functions can be used to extract or modify texts in a series**
     * Upper and Lower Function
     * Len function
     * Strip Function
     * Split Function
     * Contains Function
     * Replace Function
     * Count Function
     * Startswith and Endswith Function
     * Find Function
   * **h) Converting a Series to List**

2. **Detailed Coding Implementations on Pandas DataFrame**
   * **a) Creating Data Frames**
   * **b) Slicing in DataFrames Using Iloc and Loc**
     * Basic Loc Operations
     * Basic Iloc Operations
     * Slicing Using Conditions
   * **c) Column Addition in DataFrames**
     * Using List
     * Using Pandas Series
     * Using an Existing Column
   * **d) Deleting Column in DataFrame**
     * Using del
     * Using pop function
   * **e) Addition of rows**
   * **f) Drop function**
   * **g) Transposing a DataFrame**
   * **h) A set of more DataFrame Functionalities**
     * axes function
     * ndim function
     * dtypes function
     * shape function
     * head function
     * tail function
     * empty function
   * **i) Statistical or Mathematical Functions**
     * Sum
     * Mean
     * Median
     * Mode
     * Variance
     * Min
     * Max
     * Standard Deviation
   * **j) Describe Function**
   * **k) Pipe Functions:**
     * Pipe function
     * Apply Function
     * Applymap Function
   * **l) Reindex Function**
   * **m) Renaming Columns in Pandas DataFrame**
   * **n) Sorting in Pandas DataFrame**
   * **o) Groupby Functions**
     * Adding Statistical Computation on groupby
     * Using Filter Function with Groupby

### 1. working with pandas Series

#### **a) Creating Series**

##### Series through list

In [10]:
sr1 = pd.Series([1,2,3,4,5,6])
sr1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

##### Series through Numpy Array

In [9]:
arr = np.array([1,2,3,4,5,6])
sr2 = pd.Series(arr)
sr2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

##### Setting up our own index

In [11]:
lst = [10,20,35,25,45,26]
sr3 = pd.Series(data = lst, index = ['mayur','shaurya','rajan','anjaney','yash','anant'])
sr3

mayur      10
shaurya    20
rajan      35
anjaney    25
yash       45
anant      26
dtype: int64

##### Series through dictionary

In [12]:
dict1 = {'mayur': 10, 'shaurya':20, 'rajan' : 35, 'anjaney' : 25, 'yash' : 45, 'anant': 26}
sr4 = pd.Series(dict1)
sr4

mayur      10
shaurya    20
rajan      35
anjaney    25
yash       45
anant      26
dtype: int64

##### Using repeat function along with creating a Series

In [14]:
sr5 = pd.Series([10,5]).repeat([5,2])
sr5

0    10
0    10
0    10
0    10
0    10
1     5
1     5
dtype: int64

##### Using reset_index for proper indexing

In [15]:
sr6 = pd.Series([10,5]).repeat([5,2]).reset_index(drop = True)
sr6

0    10
1    10
2    10
3    10
4    10
5     5
6     5
dtype: int64

##### Accessing data from Series

In [17]:
print(sr6[1])

10

#### b) Aggregate function on Pandas Series

In [18]:
sr1.agg([min,max,sum])

min     1
max     6
sum    21
dtype: int64

#### c) Series Absolute Function

In [19]:
sr7 = pd.Series([1,2,-3,-4,5,6])
sr7.abs()

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

#### e) Astype Function

In [26]:
sr6.astype('float')

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5     5.0
6     5.0
dtype: float64

#### f) Between Functions

In [27]:
sr6.between(5,10)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

#### g) All strings functions can be used to extract or modify texts in a series

##### Upper Function

In [46]:
sr = pd.Series(['    mayur dange  ','    shaurya gupta'    ,'    rajan gupta   ','anjaney tiwari','yash gupta   ','anant tiwari   '])

sr.str.upper()

0         MAYUR DANGE
1         SHAURYA GUPTA
2        RAJAN GUPTA
3        ANJANEY TIWARI
4         YASH GUPTA
5       ANANT TIWARI
dtype: str

##### Lower function

In [36]:
sr.str.lower()

0      mayur
1    shaurya
2      rajan
3    anjaney
4       yash
5      anant
dtype: str

##### Len function

In [39]:
for i in sr:
    print(i, ':',len(i))

mayur : 5
shaurya : 7
rajan : 5
anjaney : 7
yash : 4
anant : 5

##### Strip Function

In [49]:
sr_new = sr.str.strip()
sr_new

0       mayur dange
1     shaurya gupta
2       rajan gupta
3    anjaney tiwari
4        yash gupta
5      anant tiwari
dtype: str

##### Split Function

In [51]:
sr_new.str.split(' ')

0       [mayur, dange]
1     [shaurya, gupta]
2       [rajan, gupta]
3    [anjaney, tiwari]
4        [yash, gupta]
5      [anant, tiwari]
dtype: object

##### Contains Function

In [52]:
sr_new.str.contains('dange')

0     True
1    False
2    False
3    False
4    False
5    False
dtype: bool

##### Replace Function

In [53]:
sr_new.str.replace('anant','harshit')

0       mayur dange
1     shaurya gupta
2       rajan gupta
3    anjaney tiwari
4        yash gupta
5    harshit tiwari
dtype: str

##### Count Function

In [54]:
sr.str.count('a')

0    2
1    3
2    3
3    3
4    2
5    3
dtype: int64

 ##### Startswith Function

In [56]:
sr_new.str.startswith('a')

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

##### Endswith function

In [58]:
sr_new.str.endswith('gupta')

0    False
1     True
2     True
3    False
4     True
5    False
dtype: bool

 ##### Find Finction

In [59]:
sr_new.str.find('gupta')

0   -1
1    8
2    6
3   -1
4    5
5   -1
dtype: int64

#### h) Converting a Series to List

In [29]:
sr6.tolist()

[10, 10, 10, 10, 10, 5, 5]

### 2. Detailed Coding implementations on Pandas DataFrame

#### a) Creating Data Frames

In [4]:
Data = {'one'   : [1, 2, 3, 4],
        'two'   : [10, 20, 30, 40],
        'three' : [100, 200, 300, 400],
        'four'  : [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data = Data)
df

   one  two  three  four
0    1   10    100  1000
1    2   20    200  2000
2    3   30    300  3000
3    4   40    400  4000

#### b) Slicing in DataFrames Using Iloc and Loc

##### Basic Loc Operations

In [6]:
df.loc[1:3, 'one':'three']

   one  two  three
1    2   20    200
2    3   30    300
3    4   40    400

In [21]:
df.loc[[1,2],['two','four']]

   two  four
1   20  2000
2   30  3000

 ##### Basic Iloc Operations

In [8]:
df.iloc[1:3, 0:2]

   one  two
1    2   20
2    3   30

In [25]:
df.iloc[[0,1],[1,2]]

   two  three
0   10    100
1   20    200

##### Slicing Using Conditions

In [7]:
df.loc[df['two'] > 20,['two']]

   two
2   30
3   40

#### c) Column Addition in DataFrames

##### Using List

In [9]:
lst = [22,44,666,555]
df['five']=lst
df

   one  two  three  four  five
0    1   10    100  1000    22
1    2   20    200  2000    44
2    3   30    300  3000   666
3    4   40    400  4000   555

##### Using Pandas Seires

In [21]:
sr = pd.Series([45,67,89,9])
df['six'] = sr
df

   one  two  three  four  five  six
0    1   10    100  1000    22   45
1    2   20    200  2000    44   67
2    3   30    300  3000   666   89
3    4   40    400  4000   555    9

##### Using an Existing Column

In [19]:
df['seven'] = df['one'] * 3
df

   one  two  three  four  five  seven
0    1   10    100  1000    22      3
1    2   20    200  2000    44      6
2    3   30    300  3000   666      9
3    4   40    400  4000   555     12

#### d) Deleting Column in DataFrame

 ##### Using del

In [20]:
del df['seven']
df

   one  two  three  four  five
0    1   10    100  1000    22
1    2   20    200  2000    44
2    3   30    300  3000   666
3    4   40    400  4000   555

##### Using pop function

In [25]:
df.pop('two')
df

   three  four  five  six
0    100  1000    22   45
1    200  2000    44   67
2    300  3000   666   89
3    400  4000   555    9

#### e) Addition of rows

In [28]:
df_app = pd.DataFrame([1,2,3,4], columns = ['one'])
df_app

   one
0    1
1    2
2    3
3    4

#### f) Drop function

In [ ]:
df.drop([0,2], axis = 0, inplace = True)

#### g) Transposing a DataFrame

In [30]:
df.T

          0     1     2     3
three   100   200   300   400
four   1000  2000  3000  4000
five     22    44   666   555
six      45    67    89     9

#### h) A set of more DataFrame Functionalities
 
 ##### axes function

In [32]:
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['three', 'four', 'five', 'six'], dtype='object')]

##### ndim function

In [33]:
df.ndim

2

 ##### dtypes function

In [34]:
df.dtypes

three    int64
four     int64
five     int64
six      int64
dtype: object

 ##### shape function

In [36]:
df.shape

(4, 4)

 ##### head function

In [39]:
df.head(2)

   three  four  five  six
0    100  1000    22   45
1    200  2000    44   67

 ##### tail function

In [40]:
df.tail(2)

   three  four  five  six
2    300  3000   666   89
3    400  4000   555    9

 ##### empty function

In [45]:
df.empty

False

#### i) Statistical or Mathematical Functions

##### Sum

In [47]:
print(df['three'].sum())

1000

##### Mean

In [48]:
print(df['three'].mean())

250.0

##### Median

In [49]:
print(df['three'].median())

250.0

##### Mode

In [50]:
print(df['three'].mode())

0    100
1    200
2    300
3    400
Name: three, dtype: int64

 ##### Variance

In [51]:
print(df['three'].var())

16666.666666666668

 ##### Min

In [52]:
print(df['three'].min())

100

##### Max

In [53]:
print(df['three'].max())

400

##### Standard Deviation

In [54]:
print(df['three'].std())

129.09944487358058

#### j) Describe Function

In [55]:
df.describe()

            three         four        five        six
count    4.000000     4.000000    4.000000   4.000000
mean   250.000000  2500.000000  321.750000  52.500000
std    129.099445  1290.994449  336.604986  34.112559
min    100.000000  1000.000000   22.000000   9.000000
25%    175.000000  1750.000000   38.500000  36.000000
50%    250.000000  2500.000000  299.500000  56.000000
75%    325.000000  3250.000000  582.750000  72.500000
max    400.000000  4000.000000  666.000000  89.000000

#### k) Pipe Functions:

In [76]:
df

   three  four  five  six
0    100  1000    22   45
1    200  2000    44   67
2    300  3000   666   89
3    400  4000   555    9

In [78]:
def add_(i,j):
    return i+j

df.pipe(add_,10)

   three  four  five  six
0    110  1010    32   55
1    210  2010    54   77
2    310  3010   676   99
3    410  4010   565   19

In [81]:
def mean(i):
    return i.mean()
def square(i):
    return i**2
print(df.pipe(mean))
print(df.pipe(mean).pipe(square))

three     250.00
four     2500.00
five      321.75
six        52.50
dtype: float64
three    6.250000e+04
four     6.250000e+06
five     1.035231e+05
six      2.756250e+03
dtype: float64

 ##### Apply Function

In [89]:
df.apply(np.mean,axis = 0)

three     250.00
four     2500.00
five      321.75
six        52.50
dtype: float64

In [85]:
df.apply(lambda x: x.max() - x.min())

three     300
four     3000
five      644
six        80
dtype: int64

##### Applymap Function

In [93]:
df.applymap(np.float64)

C:\Users\MISHAL MITTAL\AppData\Local\Temp\ipykernel_11708\4053503805.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(np.float64)

   three    four   five   six
0  100.0  1000.0   22.0  45.0
1  200.0  2000.0   44.0  67.0
2  300.0  3000.0  666.0  89.0
3  400.0  4000.0  555.0   9.0

#### l) Reindex Function

In [56]:
df.reindex([1,0,3,2])

   three  four  five  six
1    200  2000    44   67
0    100  1000    22   45
3    400  4000   555    9
2    300  3000   666   89

#### m) Renaming Columns in Pandas DataFrame

In [57]:
df.rename(columns = {'three': 'Three', 'four':'Four', 'five':'Five', 'six':'Six'})

   Three  Four  Five  Six
0    100  1000    22   45
1    200  2000    44   67
2    300  3000   666   89
3    400  4000   555    9

#### n) Sorting in Pandas DataFrame

In [60]:
df.sort_values(by = 'three', ascending = False)

   three  four  five  six
3    400  4000   555    9
2    300  3000   666   89
1    200  2000    44   67
0    100  1000    22   45

In [61]:
df.sort_values(by = ['three', 'four'], ascending = False)

   three  four  five  six
3    400  4000   555    9
2    300  3000   666   89
1    200  2000    44   67
0    100  1000    22   45

#### o) Groupby Functions

In [62]:
cricket = {'Team'   : ['India', 'India', 'Australia', 'Australia', 'SA', 'SA', 'SA', 'SA', 'NZ', 'NZ', 'NZ', 'India'],
           'Rank'   : [2, 3, 1,2, 3,4 ,1 ,1,2 , 4,1,2],
           'Year'   : [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
           'Points' : [876,801,891,815,776,784,834,824,758,691,883,782]}

df_cric = pd.DataFrame(cricket)
df_cric

         Team  Rank  Year  Points
0       India     2  2014     876
1       India     3  2015     801
2   Australia     1  2014     891
3   Australia     2  2015     815
4          SA     3  2014     776
5          SA     4  2015     784
6          SA     1  2016     834
7          SA     1  2017     824
8          NZ     2  2016     758
9          NZ     4  2014     691
10         NZ     1  2015     883
11      India     2  2017     782

In [64]:
df_cric.groupby('Team').groups

{'Australia': [2, 3], 'India': [0, 1, 11], 'NZ': [8, 9, 10], 'SA': [4, 5, 6, 7]}

In [65]:
df_cric.groupby('Team').get_group('Australia')

        Team  Rank  Year  Points
2  Australia     1  2014     891
3  Australia     2  2015     815

 ##### Adding Statistical Computation on groupby

In [67]:
df_cric.groupby('Team').sum()['Points']

Team
Australia    1706
India        2459
NZ           2332
SA           3218
Name: Points, dtype: int64

In [70]:
df_cric.groupby('Team').sum()['Points'].sort_values(ascending = False)

Team
SA           3218
India        2459
NZ           2332
Australia    1706
Name: Points, dtype: int64

 ##### Using Filter Function with Groupby

In [75]:
df_cric.groupby('Team').filter(lambda x: len(x) >= 3).sort_values(by = 'Team', ascending = True)

     Team  Rank  Year  Points
0   India     2  2014     876
1   India     3  2015     801
11  India     2  2017     782
8      NZ     2  2016     758
9      NZ     4  2014     691
10     NZ     1  2015     883
4      SA     3  2014     776
5      SA     4  2015     784
6      SA     1  2016     834
7      SA     1  2017     824